name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
      - name: Insert OpenAI API key to recipes backend
        run: |
          sed -i "s/dummykey/${{ secrets.OPENAI_KEY }}/g" app/backend/recipes/src/main/resources/application.properties
      - name: Insert WeatherAPI key to recipes backend
        run: |
          sed -i "s/dummyweatherkey/${{ secrets.WEATHERAPI_KEY }}/g" app/backend/recipes/src/main/resources/application.properties
      - name: Compose down potentially running old version
        run: docker-compose -f app/docker-compose.yml down --remove-orphans --rmi all
      - name: Compose Up
        run: docker-compose -f app/docker-compose.yml up --build --force-recreate -d
