name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  JUnit-Recipes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Preparation
      run: |
        docker-compose -f app/docker-compose.yml up --build --force-recreate -d database
        sed -i 's/database:3306/localhost:3306/' app/backend/recipes/src/main/resources/application.properties
    - name: Build
      run: mvn package -DskipTests --file app/backend/recipes/pom.xml
    - name: Test
      run: mvn test --file app/backend/recipes/pom.xml
  JUnit-Users:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Preparation
      run: |
        docker-compose -f app/docker-compose.yml up --build --force-recreate -d database
        sed -i 's/database:3306/localhost:3306/' app/backend/users/src/main/resources/application.properties
    - name: Build
      run: mvn package -DskipTests --file app/backend/users/pom.xml
    - name: Test
      run: mvn test --file app/backend/users/pom.xml
